# services/console-api/cloudbuild.yaml
substitutions:
  _REGION: "me-central1"
  _SERVICE: "console-api"
  _REPO: "apps"

steps:
  # Build image from the API folder (Dockerfile بجانب هذا الملف)
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}"
      - "."

  # Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}"

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - "--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      # أسرار لاحقًا عبر Secret Manager:
      # - "--update-secrets=API_KEY=api-key:latest"

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}"
