name: Deploy Web to Firebase Hosting (main)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseToken: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
          channelId: live
          projectId: gcdc-468918
