name: Preview Web on Firebase Hosting (PRs)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-preview:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter build (web)
        working-directory: apps/console-flutter
        run: |
          flutter pub get
          flutter build web --release

      - name: Deploy Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GCDC_468918 }}
          projectId: gcdc-468918
          expires: 7d
