name: Preview Web on Firebase Hosting (PRs)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  preview:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GCDC_468918 }}
          projectId: gcdc-468918
          expires: 7d
